### PR TITLE
🐛 Add previous `guid` to new `address`

### LINKED ISSUE #192: regression: server address key "guid=" is lost
- https://dbus.freedesktop.org/doc/dbus-specification.html#addresses
- accidentally regressed during https://github.com/dbus2/busd/pull/182

### PR DESCRIPTION
**Pull request by jokeyrhyme**
We re-add the previous `guid` value to the new `address`.

fixes #192

### CODE REVIEW

File: src/bus/mod.rs [hunk 1]
```diff
@@ -46,30 +46,40 @@ enum Listener {
...
+            address.set_guid(guid.clone())?
+        };
+        let guid: OwnedGuid = address
+            .guid()
+            .expect("Address key (guid) should already be initialized.")
+            .to_owned()
+            .into();
+
+        #[cfg(unix)]
+        let address = if let Transport::Unix(unix) = address.transport() {
```
Comment (zeenix) [inline src/bus/mod.rs:66]: I'm not sure this is a good change. We end up matching the same exact thing twice one after another. An extra level of indentation is just a price you've to pay for `match`.

File: src/bus/mod.rs [hunk 2]
```diff
@@ -46,30 +46,40 @@ enum Listener {
...
-                address = address.set_guid(guid.clone())?;
-
-                guid.into()
-            }
+        let address = if address.guid().is_some() {
+            address
+        } else {
+            let guid = Guid::generate();
+            address.set_guid(guid.clone())?
+        };
```
Comment (zeenix) [inline src/bus/mod.rs:58]: same here. Please don't switch from match to if. I find the former more readable, despite the extra level of indentation.

**Review by zeenix — CHANGES_REQUESTED** [review]
I think this can be super simple by just dropping the first commit. `address` (or any other variables can be turned mutable as a minor detail as part of the commit.

**Comment by jokeyrhyme** [comment]
Okay, I've removed the refactor commit and re-tested against zbus
